sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install cython
  - python setup.py build_ext — inplace — define CYTHON_TRACE
  
script:
  - coverage run test.py
  - coverage xml
  - cython  --annotate-coverage coverage.xml  cython_test_coverage/basic_cython.pyx

after_success:
- codecov
