sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install cython
  - python setup.py build_ext — inplace — define CYTHON_TRACE
  
script:
  - coverage run test.py

after_success:
- codecov
