sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install cython
  - python setup.py build_ext --define CYTHON_TRACE=1
  
script:
  - coverage run test.py
  - coverage xml

after_success:
- codecov
