sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install cython
  - python setup.py build_ext --define CYTHON_TRACE
  
script:
  - cython  --annotate-coverage coverage.xml  cython_test_coverage/basic_cython.pyx
  - coverage run test.py
  - coverage xml

after_success:
- codecov
